<?php

namespace Database\Seeders;

use App\Models\SubCategory;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CourseSubCategoryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $CourseSubCategoryDetails = [
            [
                'id'                => 1,
                'page_category_id'     => 1,
                'category_id'       => 1,
                'sub_category'      => 'Web Application',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 2,
                'page_category_id'     => 1,
                'category_id'       => 1,
                'sub_category'      => 'Website VAPT Testing',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 3,
                'page_category_id'     => 1,
                'category_id'       => 1,
                'sub_category'      => 'Mobile Application VAPT Testing',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 4,
                'page_category_id'     => 1,
                'category_id'       => 1,
                'sub_category'      => 'Thick Client VAPT Testing',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 5,
                'page_category_id'     => 1,
                'category_id'       => 1,
                'sub_category'      => 'EPR System and Business Application VAPT Testing',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 6,
                'page_category_id'     => 1,
                'category_id'       => 1,
                'sub_category'      => 'API VAPT Testing',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 7,
                'page_category_id'     => 1,
                'category_id'       => 1,
                'sub_category'      => 'Network Security Architecture Review',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 8,
                'page_category_id'     => 1,
                'category_id'       => 1,
                'sub_category'      => 'Network VAPT Testing – Internal and External',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 9,
                'page_category_id'     => 1,
                'category_id'       => 1,
                'sub_category'      => 'Firewall VAPT Testing',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 10,
                'page_category_id'     => 1,
                'category_id'       => 1,
                'sub_category'      => 'Cloud VAPT Testing',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 11,
                'page_category_id'     => 1,
                'category_id'       => 1,
                'sub_category'      => 'Wireless Network VAPT Testing',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 12,
                'page_category_id'     => 1,
                'category_id'       => 1,
                'sub_category'      => 'ICS - SCADA VAPT Testing',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 13,
                'page_category_id'     => 1,
                'category_id'       => 1,
                'sub_category'      => 'IoT VAPT Testing',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 14,
                'page_category_id'     => 1,
                'category_id'       => 1,
                'sub_category'      => 'VoIP/SIP VAPT Testing',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 15,
                'page_category_id'     => 1,
                'category_id'       => 1,
                'sub_category'      => 'Source Code Review',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 16,
                'page_category_id'     => 1,
                'category_id'       => 1,
                'sub_category'      => 'Configuration & Hardening Security',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 17,
                'page_category_id'     => 1,
                'category_id'       => 1,
                'sub_category'      => 'Open-source Intelligence (OSINT) Testing',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 18,
                'page_category_id'     => 1,
                'category_id'       => 1,
                'sub_category'      => 'Binary Tools & Binary Code Analysis',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],

            [
                'id'                => 19,
                'page_category_id'     => 1,
                'category_id'       => 2,
                'sub_category'      => 'ISO 27001 (ISMS) Consulting and Advisory',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 20,
                'page_category_id'     => 1,
                'category_id'       => 2,
                'sub_category'      => 'ISO 22301 (BCMS) Consulting and Advisory',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 21,
                'page_category_id'     => 1,
                'category_id'       => 2,
                'sub_category'      => 'ISO 20000 (ITSM) Consulting and Advisory',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 22,
                'page_category_id'     => 1,
                'category_id'       => 2,
                'sub_category'      => 'ISO 27701 (PIMS) Consulting and Advisory',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 23,
                'page_category_id'     => 1,
                'category_id'       => 2,
                'sub_category'      => 'PCI-DSS, PA-DSS and PCI-CPP Consulting and Advisory',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 24,
                'page_category_id'     => 1,
                'category_id'       => 2,
                'sub_category'      => 'GDPR Compliance Consulting and Advisory',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 25,
                'page_category_id'     => 1,
                'category_id'       => 2,
                'sub_category'      => 'India Data Protection Act - PDPA Consulting and Advisory',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 26,
                'page_category_id'     => 1,
                'category_id'       => 2,
                'sub_category'      => 'California Consumer Privacy Act (CCPA) Consulting and Advisory',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 27,
                'page_category_id'     => 1,
                'category_id'       => 2,
                'sub_category'      => 'SOC 2 Compliance Consulting and Advisory',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 28,
                'page_category_id'     => 1,
                'category_id'       => 2,
                'sub_category'      => 'HIPAA Compliance Consulting and Advisory',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 29,
                'page_category_id'     => 1,
                'category_id'       => 2,
                'sub_category'      => 'GAP Assessment Service',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 30,
                'page_category_id'     => 1,
                'category_id'       => 2,
                'sub_category'      => 'Risk Assessment Service',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 31,
                'page_category_id'     => 1,
                'category_id'       => 3,
                'sub_category'      => 'RBI Compliance Audit',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 32,
                'page_category_id'     => 1,
                'category_id'       => 3,
                'sub_category'      => 'IRDA ISNP Compliance Audit for Insurance Sector',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 33,
                'page_category_id'     => 1,
                'category_id'       => 3,
                'sub_category'      => 'Aadhaar Compliance (UIDAI AUA/KUA) Compliance Audit',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 34,
                'page_category_id'     => 1,
                'category_id'       => 3,
                'sub_category'      => 'eSign ASP Compliance Audit',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 35,
                'page_category_id'     => 1,
                'category_id'       => 3,
                'sub_category'      => 'SEBI System Audit and Cyber Resilience Framework Audit',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 36,
                'page_category_id'     => 1,
                'category_id'       => 3,
                'sub_category'      => 'GST Suvidha Providers System Audit',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 37,
                'page_category_id'     => 1,
                'category_id'       => 3,
                'sub_category'      => 'NPCI Compliance Audit',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 38,
                'page_category_id'     => 1,
                'category_id'       => 4,
                'sub_category'      => 'Functional Testing',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 39,
                'page_category_id'     => 1,
                'category_id'       => 4,
                'sub_category'      => 'Performance Testing',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 40,
                'page_category_id'     => 1,
                'category_id'       => 4,
                'sub_category'      => 'Devops Testing',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 41,
                'page_category_id'     => 1,
                'category_id'       => 4,
                'sub_category'      => 'STQC Certification',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 42,
                'page_category_id'     => 1,
                'category_id'       => 5,
                'sub_category'      => 'GIGW Compliance Testing',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 43,
                'page_category_id'     => 1,
                'category_id'       => 5,
                'sub_category'      => 'WCAG Compliance Testing',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 44,
                'page_category_id'     => 1,
                'category_id'       => 5,
                'sub_category'      => 'VPAT Compliance Testing',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 45,
                'page_category_id'     => 1,
                'category_id'       => 6,
                'sub_category'      => 'Red Teaming',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 46,
                'page_category_id'     => 1,
                'category_id'       => 6,
                'sub_category'      => 'Blue Teaming',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 47,
                'page_category_id'     => 1,
                'category_id'       => 6,
                'sub_category'      => 'Cloud Security Management Services',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 48,
                'page_category_id'     => 1,
                'category_id'       => 6,
                'sub_category'      => 'Data Security Management Services',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 49,
                'page_category_id'     => 1,
                'category_id'       => 6,
                'sub_category'      => 'Data Migration Audit and Review',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 50,
                'page_category_id'     => 1,
                'category_id'       => 6,
                'sub_category'      => 'Malware and Incident Response Analysis Service',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 51,
                'page_category_id'     => 1,
                'category_id'       => 6,
                'sub_category'      => 'Phishing Campaign and Social Engineering Service',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 52,
                'page_category_id'     => 1,
                'category_id'       => 6,
                'sub_category'      => 'User Awareness Campaign',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 53,
                'page_category_id'     => 1,
                'category_id'       => 6,
                'sub_category'      => 'Forensic Investigation Services',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 54,
                'page_category_id'     => 1,
                'category_id'       => 6,
                'sub_category'      => 'Secure DevOPs / DevSecOps',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 55,
                'page_category_id'     => 1,
                'category_id'       => 7,
                'sub_category'      => 'Endpoint Protection for SMB',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 56,
                'page_category_id'     => 1,
                'category_id'       => 7,
                'sub_category'      => 'Complete Security for Business',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 57,
                'page_category_id'     => 1,
                'category_id'       => 7,
                'sub_category'      => 'Next Generation Firewall',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 58,
                'page_category_id'     => 1,
                'category_id'       => 7,
                'sub_category'      => 'Data Leakage Protection',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],

            [
                'id'                => 59,
                'page_category_id'     => 1,
                'category_id'       => 7,
                'sub_category'      => 'SIEM Solutions',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 60,
                'page_category_id'     => 1,
                'category_id'       => 7,
                'sub_category'      => 'Web Protection',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 61,
                'page_category_id'     => 1,
                'category_id'       => 7,
                'sub_category'      => 'E-Mail Protection',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 62,
                'page_category_id'     => 1,
                'category_id'       => 7,
                'sub_category'      => 'Mobile Device Management',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 63,
                'page_category_id'     => 1,
                'category_id'       => 7,
                'sub_category'      => 'One Time Password Solutions',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 64,
                'page_category_id'     => 1,
                'category_id'       => 7,
                'sub_category'      => 'Virtual CISO Services',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 65,
                'page_category_id'     => 1,
                'category_id'       => 7,
                'sub_category'      => 'Cyber Security Insurance',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 66,
                'page_category_id'     => 1,
                'category_id'       => 8,
                'sub_category'      => 'Security Information and Event Management (SIEM) Monitoring',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 67,
                'page_category_id'     => 1,
                'category_id'       => 8,
                'sub_category'      => 'Insider Threat Monitoring',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 68,
                'page_category_id'     => 1,
                'category_id'       => 8,
                'sub_category'      => 'Process System Control/SCADA Monitoring',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 69,
                'page_category_id'     => 1,
                'category_id'       => 8,
                'sub_category'      => 'Security Device Management',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 70,
                'page_category_id'     => 1,
                'category_id'       => 8,
                'sub_category'      => 'Rapid Threat Containment',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 71,
                'page_category_id'     => 1,
                'category_id'       => 9,
                'sub_category'      => 'Burp Suite Professional
',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 72,
                'page_category_id'     => 1,
                'category_id'       => 9,
                'sub_category'      => 'Acunetix',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 73,
                'page_category_id'     => 1,
                'category_id'       => 9,
                'sub_category'      => 'Nessus',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 74,
                'page_category_id'     => 1,
                'category_id'       => 9,
                'sub_category'      => 'Seqrite',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 75,
                'page_category_id'     => 1,
                'category_id'       => 9,
                'sub_category'      => 'McAfee',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 76,
                'page_category_id'     => 1,
                'category_id'       => 9,
                'sub_category'      => 'Symantec',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 77,
                'page_category_id'     => 1,
                'category_id'       => 9,
                'sub_category'      => 'Sophos',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 78,
                'page_category_id'     => 1,
                'category_id'       => 9,
                'sub_category'      => 'Checkmarx',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 79,
                'page_category_id'     => 1,
                'category_id'       => 9,
                'sub_category'      => 'O-Phish',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 80,
                'page_category_id'     => 2,
                'category_id'       => 10,
                'sub_category'      => 'Certified Network Defender (CND)',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 81,
                'page_category_id'     => 2,
                'category_id'       => 10,
                'sub_category'      => 'Certified Ethical Hacker (CEH)',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 82,
                'page_category_id'     => 2,
                'category_id'       => 10,
                'sub_category'      => ' Certified Security Analyst (ECSA)',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 83,
                'page_category_id'     => 2,
                'category_id'       => 10,
                'sub_category'      => 'Licensed Penetration Tester (LPT)',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 84,
                'page_category_id'     => 2,
                'category_id'       => 10,
                'sub_category'      => 'Computer Hacking Forensic Investigator (CHFI)',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 85,
                'page_category_id'     => 2,
                'category_id'       => 10,
                'sub_category'      => 'Certified SOC Analyst (CSA)',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 86,
                'page_category_id'     => 2,
                'category_id'       => 10,
                'sub_category'      => 'Certified Incident Handler (ECIH)',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 87,
                'page_category_id'     => 2,
                'category_id'       => 10,
                'sub_category'      => 'Certified Threat Intelligence Analyst (CTIA)',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 88,
                'page_category_id'     => 2,
                'category_id'       => 10,
                'sub_category'      => 'Certified Encryption Specialist (ECES)',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 89,
                'page_category_id'     => 2,
                'category_id'       => 10,
                'sub_category'      => 'Certified Application Security Engineer - Java or .NET (CASE)',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 90,
                'page_category_id'     => 2,
                'category_id'       => 10,
                'sub_category'      => 'Disaster Recovery Professional (EDRP)',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 91,
                'page_category_id'     => 2,
                'category_id'       => 10,
                'sub_category'      => 'Certified Chief Information Security Professional (CCISO)
',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 92,
                'page_category_id'     => 2,
                'category_id'       => 11,
                'sub_category'      => 'GDPR (Certified Data Protection Officer)',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 93,
                'page_category_id'     => 2,
                'category_id'       => 11,
                'sub_category'      => 'ISO/IEC 27001 (ISMS)',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 94,
                'page_category_id'     => 2,
                'category_id'       => 11,
                'sub_category'      => 'ISO/IEC 27005 (Information Security Risk Management)',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 95,
                'page_category_id'     => 2,
                'category_id'       => 11,
                'sub_category'      => 'ISO/IEC 27034 Lead (Application Security)',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 96,
                'page_category_id'     => 2,
                'category_id'       => 11,
                'sub_category'      => 'SCADA Security Manager', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 97,
                'page_category_id'     => 2,
                'category_id'       => 11,
                'sub_category'      => 'Digitalization and Electronic Archiving Manager', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 98,
                'page_category_id'     => 2,
                'category_id'       => 11,
                'sub_category'      => 'ISO 31000 (Risk Management)', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 99,
                'page_category_id'     => 2,
                'category_id'       => 11,
                'sub_category'      => 'ISO 37001 (Anti-Bribery)', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],

            [
                'id'                => 100,
                'page_category_id'     => 2,
                'category_id'       => 11,
                'sub_category'      => 'ISO 22301 (Business Continuity Management System)', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 101,
                'page_category_id'     => 2,
                'category_id'       => 11,
                'sub_category'      => 'Disaster Recovery', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 102,
                'page_category_id'     => 2,
                'category_id'       => 11,
                'sub_category'      => 'ISO/IEC 38500 (IT Governance)', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 103,
                'page_category_id'     => 2,
                'category_id'       => 11,
                'sub_category'      => 'ISO 20000 (IT Service Management System)', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 104,
                'page_category_id'     => 2,
                'category_id'       => 11,
                'sub_category'      => 'ISO 21500 (Project Management)', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 105,
                'page_category_id'     => 2,
                'category_id'       => 11,
                'sub_category'      => 'ISO 27035 (Incident Management)', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 106,
                'page_category_id'     => 2,
                'category_id'       => 11,
                'sub_category'      => 'ISO 28000 (Supply Chain Security Management System)', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 107,
                'page_category_id'     => 2,
                'category_id'       => 11,
                'sub_category'      => 'Six Sigma Certifications', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 108,
                'page_category_id'     => 2,
                'category_id'       => 11,
                'sub_category'      => 'ISO 9001 (Quality Management System)', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 109,
                'page_category_id'     => 2,
                'category_id'       => 11,
                'sub_category'      => 'ISO 13485 (Medical Devices Quality Management)', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 110,
                'page_category_id'     => 2,
                'category_id'       => 11,
                'sub_category'      => 'ISO/IEC 17025 (Laboratory Management System)', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 111,
                'page_category_id'     => 2,
                'category_id'       => 11,
                'sub_category'      => 'AS9100 (Aerospace Quality Management)', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 112,
                'page_category_id'     => 2,
                'category_id'       => 11,
                'sub_category'      => 'IATF 16949 Quality Management', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 113,
                'page_category_id'     => 2,
                'category_id'       => 11,
                'sub_category'      => 'ISO/TS 29001 (Oil and Gas Quality Management)', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 114,
                'page_category_id'     => 2,
                'category_id'       => 11,
                'sub_category'      => 'ISO 50001 (Energy Management System)', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 115,
                'page_category_id'     => 2,
                'category_id'       => 11,
                'sub_category'      => 'ISO 22000 (Food Safety Management System)', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 116,
                'page_category_id'     => 2,
                'category_id'       => 11,
                'sub_category'      => 'OHSAS 18001 (Occupational Health and Safety Management System)', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 117,
                'page_category_id'     => 2,
                'category_id'       => 11,
                'sub_category'      => 'ISO 21001 (Educational Organizations Management)', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 118,
                'page_category_id'     => 2,
                'category_id'       => 11,
                'sub_category'      => 'ISO 26000 (Social Responsibility)', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 119,
                'page_category_id'     => 2,
                'category_id'       => 12,
                'sub_category'      => 'Security Assessment and Penetration Testing (VAPT)', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 120,
                'page_category_id'     => 2,
                'category_id'       => 12,
                'sub_category'      => 'Cloud Security', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 121,
                'page_category_id'     => 2,
                'category_id'       => 12,
                'sub_category'      => 'Security Operations and Management', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 122,
                'page_category_id'     => 2,
                'category_id'       => 12,
                'sub_category'      => 'Cyber Forensic and Fraud Management', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 123,
                'page_category_id'     => 2,
                'category_id'       => 12,
                'sub_category'      => 'Security Technology & Vendor Specfic Training', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 124,
                'page_category_id'     => 2,
                'category_id'       => 13,
                'sub_category'      => 'BIG DATA ANALYTICS', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 125,
                'page_category_id'     => 2,
                'category_id'       => 13,
                'sub_category'      => 'BUSINESS INTELLIGENCE(BI)', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 126,
                'page_category_id'     => 2,
                'category_id'       => 13,
                'sub_category'      => 'SCADA Security Manager', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 127,
                'page_category_id'     => 2,
                'category_id'       => 13,
                'sub_category'      => 'DATA SCIENCE', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 128,
                'page_category_id'     => 2,
                'category_id'       => 13,
                'sub_category'      => 'ARTIFICIAL INTELLIGENCE', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 129,
                'page_category_id'     => 2,
                'category_id'       => 14,
                'sub_category'      => 'ROBOTICS PROCESS AUTOMATION', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 130,
                'page_category_id'     => 2,
                'category_id'       => 14,
                'sub_category'      => 'BLOCK CHAIN & IOT', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 131,
                'page_category_id'     => 2,
                'category_id'       => 14,
                'sub_category'      => 'DATA WAREHOUSING & ETL', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 132,
                'page_category_id'     => 2,
                'category_id'       => 14,
                'sub_category'      => 'Digitalization and Electronic Archiving', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 133,
                'page_category_id'     => 2,
                'category_id'       => 15,
                'sub_category'      => 'ISO 20000 (IT Service Management System)', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 134,
                'page_category_id'     => 2,
                'category_id'       => 15,
                'sub_category'      => 'ISO 21500 (Project Management)', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 135,
                'page_category_id'     => 2,
                'category_id'       => 15,
                'sub_category'      => 'Six Sigma Certifications', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 136,
                'page_category_id'     => 2,
                'category_id'       => 15,
                'sub_category'      => 'Scrum Master', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 137,
                'page_category_id'     => 2,
                'category_id'       => 15,
                'sub_category'      => 'Agile Testing', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 138,
                'page_category_id'     => 2,
                'category_id'       => 16,
                'sub_category'      => 'EC Council Certification Programs', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 139,
                'page_category_id'     => 2,
                'category_id'       => 16,
                'sub_category'      => 'ISACA Trainings Programs', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 140,
                'page_category_id'     => 2,
                'category_id'       => 16,
                'sub_category'      => 'ISC2 Training Programs', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 141,
                'page_category_id'     => 2,
                'category_id'       => 16,
                'sub_category'      => 'ISO/IEC 27001 (ISMS)', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 142,
                'page_category_id'     => 2,
                'category_id'       => 16,
                'sub_category'      => 'ISO/IEC 27005 (Information Security Risk Management)', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 143,
                'page_category_id'     => 2,
                'category_id'       => 16,
                'sub_category'      => 'ISO/IEC 38500 (IT Governance)', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 144,
                'page_category_id'     => 2,
                'category_id'       => 16,
                'sub_category'      => 'ISO 22301 (Business Continuity Management System)', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 145,
                'page_category_id'     => 2,
                'category_id'       => 16,
                'sub_category'      => 'Disaster Recovery', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 146,
                'page_category_id'     => 2,
                'category_id'       => 16,
                'sub_category'      => 'GDPR (Certified Data Protection Officer)', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 147,
                'page_category_id'     => 2,
                'category_id'       => 16,
                'sub_category'      => 'SCADA Security Manager', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 148,
                'page_category_id'     => 2,
                'category_id'       => 16,
                'sub_category'      => 'HIPAA Privacy and Security Awareness Program', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 149,
                'page_category_id'     => 2,
                'category_id'       => 16,
                'sub_category'      => 'PCI-DSS Awareness Program', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 150,
                'page_category_id'     => 2,
                'category_id'       => 16,
                'sub_category'      => 'SOX Awareness Program', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 151,
                'page_category_id'     => 2,
                'category_id'       => 17,
                'sub_category'      => 'Quality Management System (ISO 9001)', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 152,
                'page_category_id'     => 2,
                'category_id'       => 17,
                'sub_category'      => 'Medical Devices Quality Management  System (ISO 13485)', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 153,
                'page_category_id'     => 2,
                'category_id'       => 17,
                'sub_category'      => 'Laboratory Management System (ISO/IEC 17025)', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 154,
                'page_category_id'     => 2,
                'category_id'       => 17,
                'sub_category'      => 'Aerospace Industry Quality Management (AS9100)', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 155,
                'page_category_id'     => 2,
                'category_id'       => 17,
                'sub_category'      => 'International Automotive Task Force - IATF Quality Management (IATF 16949)', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 156,
                'page_category_id'     => 2,
                'category_id'       => 17,
                'sub_category'      => 'Oil and Gas Industry Quality Management (ISO/TS 29001)', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 157,
                'page_category_id'     => 2,
                'category_id'       => 17,
                'sub_category'      => 'Energy Management System (ISO 50001)', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 158,
                'page_category_id'     => 2,
                'category_id'       => 17,
                'sub_category'      => 'Food Safety Management System (ISO 22000)', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 159,
                'page_category_id'     => 2,
                'category_id'       => 17,
                'sub_category'      => 'Occupational Health and Safety Management System (OHSAS 18001)', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 160,
                'page_category_id'     => 2,
                'category_id'       => 17,
                'sub_category'      => 'Educational Organizations Management (ISO 21001)', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 161,
                'page_category_id'     => 2,
                'category_id'       => 17,
                'sub_category'      => 'Social Responsibility Management (ISO 26000)', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 162,
                'page_category_id'     => 2,
                'category_id'       => 18,
                'sub_category'      => 'Server Administration', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 163,
                'page_category_id'     => 2,
                'category_id'       => 18,
                'sub_category'      => 'Cloud Computing', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 164,
                'page_category_id'     => 2,
                'category_id'       => 18,
                'sub_category'      => 'DevOps', 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],



            

                     
           
                       
        ];

        SubCategory::insert($CourseSubCategoryDetails);
    }
}
