<?php

namespace Database\Seeders;

use App\Models\CourseCategory;
use Illuminate\Database\Seeder;

class CourseCategoryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $CourseCategoryDetails = [
            [
                'id'                => 1,
                'page_category'     => 1,
                'name'              => 'Security Assessment Testing',
                'slug'              => 'security-assessment-testing',
                'title'             => 'Security Assessment Testing',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 2,
                'page_category'     => 1,
                'name'              => 'Security Consulting and Advisory',
                'slug'              => 'security-consulting-and-advisory',
                'title'             => 'Security Consulting and Advisory',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 3,
                'page_category'     => 1,
                'name'              => 'Security Governance and Compliance',
                'slug'              => 'security-governance-and-compliance',
                'title'             => 'Security Governance and Compliance',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 4,
                'page_category'     => 1,
                'name'              => 'Software Testing',
                'slug'              => 'software-testing',
                'title'             => 'Software Testing',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 5,
                'page_category'     => 1,
                'name'              => 'Application Accessibility Testing',
                'slug'              => 'application-accessibility-testing',
                'title'             => 'Application Accessibility Testing',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 6,
                'page_category'     => 1,
                'name'              => 'Specialized Services',
                'slug'              => 'specialized-services',
                'title'             => 'Specialized Services',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 7,
                'page_category'     => 1,
                'name'              => 'Managed Security Services',
                'slug'              => 'managed-security-services',
                'title'             => 'Managed Security Services',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 8,
                'page_category'     => 1,
                'name'              => 'SOC as a Service',
                'slug'              => 'soc-as-a-service',
                'title'             => 'SOC as a Service',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 9,
                'page_category'     => 1,
                'name'              => 'Next Generation Information Security Solutions',
                'slug'              => 'next-generation-information-security-solutions',
                'title'             => 'Next Generation Information Security Solutions',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 10,
                'page_category'     => 2,
                'name'              => 'EC Council Accredited Certification Programs',
                'slug'              => 'ec-council-accredited-certification-programs',
                'title'             => 'EC Council Accredited Certification Programs',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 11,
                'page_category'     => 2,
                'name'              => 'PECB Accredited Certification Programs',
                'slug'              => 'pecb-accredited-certification-programs',
                'title'             => 'PECB Accredited Certification Programs',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 12,
                'page_category'     => 2,
                'name'              => 'Information security industry specialized Training',
                'slug'              => 'information-security-industry-specialized-training',
                'title'             => 'Information security industry specialized Training',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 13,
                'page_category'     => 2,
                'name'              => 'Data Science & Business Analytics',
                'slug'              => 'data-science-business-analytics',
                'title'             => 'Data Science & Business Analytics',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 14,
                'page_category'     => 2,
                'name'              => 'DIGITAL TRANSFORMATION',
                'slug'              => 'digital-transformation',
                'title'             => 'DIGITAL TRANSFORMATION',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 15,
                'page_category'     => 2,
                'name'              => 'IT Operation, Project and Service Management',
                'slug'              => 'it-operation-project-service-management',
                'title'             => 'IT Operation, Project and Service Management',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 16,
                'page_category'     => 2,
                'name'              => 'IT / Security Risk, Compliance and Governance',
                'slug'              => 'it-security-risk-compliance-governance',
                'title'             => 'IT / Security Risk, Compliance and Governance',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 17,
                'page_category'     => 2,
                'name'              => 'Industry Specific Quality Management Programs',
                'slug'              => 'industry-specific-quality-management-programs',
                'title'             => 'Industry Specific Quality Management Programs',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 18,
                'page_category'     => 2,
                'name'              => 'Server, Storage, Cloud and Virtualization',
                'slug'              => 'server-storage-cloud-virtualization',
                'title'             => 'Server, Storage, Cloud and Virtualization',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 19,
                'page_category'     => 3,
                'name'              => 'EC Council Accredited',
                'slug'              => 'ec-council-accredited',
                'title'             => 'EC Council Accredited',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 20,
                'page_category'     => 3,
                'name'              => 'PECB Accredited',
                'slug'              => 'pecb-accredited',
                'title'             => 'PECB Accredited',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 21,
                'page_category'     => 3,
                'name'              => 'Information security industry specialized Training',
                'slug'              => 'information-security-industry-specialized-training',
                'title'             => 'Information security industry specialized Training',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 22,
                'page_category'     => 3,
                'name'              => 'IT / Security Risk, Compliance and Governance',
                'slug'              => 'it-security-risk-compliance-governance',
                'title'             => 'IT / Security Risk, Compliance and Governance',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 23,
                'page_category'     => 3,
                'name'              => 'Data Science & Business Analytics',
                'slug'              => 'data-science-business-analytics',
                'title'             => 'Data Science & Business Analytics',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 24,
                'page_category'     => 3,
                'name'              => 'Digital Transformation',
                'slug'              => 'digital-transformation',
                'title'             => 'Digital Transformation',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 25,
                'page_category'     => 3,
                'name'              => 'IT Operation, Project and Service Management',
                'slug'              => 'it-operation-project-service-management',
                'title'             => 'IT Operation, Project and Service Management',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 26,
                'page_category'     => 3,
                'name'              => 'Industry Specific Quality Management Program',
                'slug'              => 'industry-specific-quality-management-program',
                'title'             => 'Industry Specific Quality Management Program',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'id'                => 27,
                'page_category'     => 3,
                'name'              => 'Server, Storage, Cloud and Virtualization',
                'slug'              => 'server-storage-cloud-virtualization',
                'title'             => 'Server, Storage, Cloud and Virtualization',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
        ];

        CourseCategory::insert($CourseCategoryDetails);
    }
}
